# Generated by Django 3.0 on 2019-12-15 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=128, verbose_name='Название работы')),
                ('createdatetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('order', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tagtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=128, verbose_name='Название работы')),
                ('order', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Taglink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdatetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('jtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jtag', to='jobqueue.Jobs', verbose_name='Задание')),
                ('ttag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttag', to='jobqueue.Tagtype', verbose_name='Тег')),
            ],
            options={
                'ordering': ['createdatetime'],
            },
        ),
    ]
