# Generated by Django 3.0 on 2019-12-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
