# Generated by Django 3.0 on 2019-12-19 20:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('jobqueue', '0003_auto_20191219_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='name',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Название тега'),
        ),
        migrations.DeleteModel(
            name='Taglink',
        ),
    ]
