# Generated by Django 3.0 on 2019-12-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0006_auto_20191220_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtype',
            name='icon',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Иконка'),
        ),
    ]
