# Generated by Django 3.0 on 2019-12-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0008_auto_20191220_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtype',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название тега'),
        ),
    ]
