# Generated by Django 3.0 on 2019-12-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0009_auto_20191220_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='icon2',
            field=models.CharField(db_index=True, default='&#xf046;', max_length=20, verbose_name='Иконка2'),
        ),
    ]
