# Generated by Django 3.0 on 2019-12-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0010_tagtype_icon2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagtype',
            name='icon',
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='icon2',
            field=models.CharField(choices=[('&#xf042;', '&#xf042;'), ('&#xf043;', '&#xf043;')], db_index=True, default='&#xf046;', max_length=20, verbose_name='Иконка'),
        ),
    ]
