# Generated by Django 3.0 on 2019-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0012_auto_20191220_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtype',
            name='icon2',
            field=models.CharField(blank=True, db_index=True, default='&#xf046;', max_length=100, null=True, verbose_name='Иконка'),
        ),
    ]
