# Generated by Django 3.0 on 2019-12-22 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0013_auto_20191220_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='shipmentdatetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время отгрузки'),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='icon2',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Иконка'),
        ),
    ]
