# Generated by Django 3.0 on 2019-12-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0015_auto_20191223_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='seton',
            field=models.BooleanField(default=False, help_text='Операция может занять много времени при большом количестве задач в БД.', verbose_name='Установить для существующих задач'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='customer',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='Заказчик'),
        ),
    ]
