# Generated by Django 3.0 on 2019-12-24 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0016_auto_20191224_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Название цвета')),
                ('text', models.CharField(db_index=True, default='#000000', max_length=8, verbose_name='Цвет текста')),
                ('bg', models.CharField(db_index=True, default='#FFFFFF', max_length=8, verbose_name='Цвет фона')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobqueue.Colors', verbose_name='Цвет'),
        ),
    ]
