# Generated by Django 3.0 on 2019-12-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0017_auto_20191225_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='colors',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
