# Generated by Django 3.0 on 2019-12-29 23:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('jobqueue', '0019_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rights',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
