# Generated by Django 3.0 on 2020-02-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0020_profile_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='techop',
            field=models.BooleanField(default=False, verbose_name='Технологическая операция'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Пример: +38(067) 123-44-55', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
