# Generated by Django 3.0 on 2020-03-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0022_auto_20200305_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobqueue.Colors', verbose_name='Цвет'),
        ),
    ]
