# Generated by Django 3.0 on 2020-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0024_auto_20200324_2108'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jobs',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='newtag',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='newtag'),
        ),
    ]
