# Generated by Django 3.0 on 2020-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0025_auto_20200324_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='newtag',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='newtag'),
        ),
    ]
