# Generated by Django 3.0 on 2020-03-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0026_auto_20200324_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newrights',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='newrights'),
        ),
    ]
