# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-25 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueue', '0027_profile_newrights'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='icon3',
            field=models.TextField(blank=True, null=True, verbose_name='Иконка своя'),
        ),
    ]
